
#Aplication Configuration
server:
  port: 8091

#H2 Console
#http://localhost:8091/h2-console
#Enabled H2 Console

spring:
  hs:
    console:
      enabled: true

  #========================
    #DB
  #=======================
  datasource:
    url: jdbc:h2:mem:productDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    plataform: h2
    username: sa
    password:

  #========================
   #JPA - HIBERNATE
  #=======================
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      database-plataform: org.hibernate.dialect.H2Dialect
      properties:
        hibernate:
          show_sql: true
          use_sql_comments: false
          format_sql: false
loggin:
   pattern:
     console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

